In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores     ...       px_height  px_width   ram  sc_h  sc_w  \
0        188        2     ...              20       756  2549     9     7   
1        136        3     ...             905      1988  2631    17     3   
2        145        5     ...            1263      1716  2603    11     2   
3        131        6     ...            1216      1786  2769    16     8   
4        141        2     ...            1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [4]:
Counter(train.price_range)

Counter({1: 500, 2: 500, 3: 500, 0: 500})

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
battery_power    2000 non-null int64
blue             2000 non-null int64
clock_speed      2000 non-null float64
dual_sim         2000 non-null int64
fc               2000 non-null int64
four_g           2000 non-null int64
int_memory       2000 non-null int64
m_dep            2000 non-null float64
mobile_wt        2000 non-null int64
n_cores          2000 non-null int64
pc               2000 non-null int64
px_height        2000 non-null int64
px_width         2000 non-null int64
ram              2000 non-null int64
sc_h             2000 non-null int64
sc_w             2000 non-null int64
talk_time        2000 non-null int64
three_g          2000 non-null int64
touch_screen     2000 non-null int64
wifi             2000 non-null int64
price_range      2000 non-null int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB


In [6]:
#x_train=train[['battery_power','int_memory','px_height','px_width','ram','blue','dual_sim','fc','four_g','touch_screen','wifi']]
x_train=train.iloc[:,0:20]
y_train=train.iloc[:,-1].values

#x_test=test[['battery_power','int_memory','px_height','px_width','ram','blue','dual_sim','fc','four_g','touch_screen','wifi']]
x_test=test.iloc[:,1:21]
y_train=y_train.reshape(-1,1)
print(x_train.shape)
print(x_test.shape)
print(y_train)

(2000, 20)
(1000, 20)
[[1]
 [2]
 [2]
 ...
 [3]
 [0]
 [3]]


In [7]:
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
#print(x_test)
onehot=OneHotEncoder(categorical_features=[0])
y_train=onehot.fit_transform(y_train).toarray()
print(y_train)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [8]:
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\Users\KIIT\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [10]:
#kfold = KFold(n_splits=20, shuffle=True, random_state=42)
#for train, test in kfold.split(X_train, y_train):
classifier=Sequential()
classifier.add(Dense(output_dim=7,init='uniform',activation='relu',input_dim=20))
classifier.add(Dense(output_dim=7,init='uniform',activation='relu'))
#classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
classifier.add(Dense(output_dim=4,init='uniform',activation='softmax'))
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
classifier.fit(X_train,y_train,epochs=60,batch_size=10)
pred=classifier.predict_classes(x_test)

C:\Users\KIIT\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=20, units=7, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\KIIT\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=7, kernel_initializer="uniform")`
  """
C:\Users\KIIT\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=4, kernel_initializer="uniform")`
  import sys


Epoch 1/60
2000/2000 [==============================] - 1s 347us/step - loss: 1.3543 - acc: 0.3505
Epoch 2/60
2000/2000 [==============================] - 1s 288us/step - loss: 0.9057 - acc: 0.5200
Epoch 3/60
2000/2000 [==============================] - 0s 183us/step - loss: 0.6399 - acc: 0.6930
Epoch 4/60
2000/2000 [==============================] - 0s 150us/step - loss: 0.4407 - acc: 0.8905
Epoch 5/60
2000/2000 [==============================] - ETA: 0s - loss: 0.2946 - acc: 0.939 - 0s 148us/step - loss: 0.2904 - acc: 0.9405
Epoch 6/60
2000/2000 [==============================] - 1s 280us/step - loss: 0.2158 - acc: 0.9530
Epoch 7/60
2000/2000 [==============================] - 0s 237us/step - loss: 0.1739 - acc: 0.9660
Epoch 8/60
2000/2000 [==============================] - 0s 166us/step - loss: 0.1508 - acc: 0.9635
Epoch 9/60
2000/2000 [==============================] - 1s 315us/step - loss: 0.1342 - acc: 0.9680 1s - loss: 0.1207 - ac
Epoch 10/60
2000/2000 [=========================

In [11]:
print(pred)

[3 3 2 3 1 3 3 1 3 0 3 3 0 0 2 0 2 1 3 2 1 3 1 1 3 0 2 0 3 0 2 0 3 0 1 1 3
 1 2 1 1 2 0 0 0 1 0 3 1 2 1 0 3 0 3 1 3 1 1 3 3 3 0 1 1 1 2 3 1 2 1 2 2 3
 3 0 2 0 2 3 0 3 3 0 3 0 3 1 3 0 1 2 2 1 2 2 1 2 1 2 1 0 0 3 0 2 0 1 2 3 3
 2 1 3 3 3 3 2 3 0 0 3 2 1 2 0 3 2 2 2 0 2 2 1 3 1 1 0 3 2 1 2 1 2 2 3 3 3
 2 3 2 3 1 0 3 2 3 3 3 3 3 2 3 3 3 3 1 0 3 0 0 0 2 1 0 1 0 0 1 2 1 0 0 1 1
 2 2 1 0 0 0 1 0 3 1 0 2 2 3 3 1 2 2 2 3 2 2 1 0 0 1 3 0 2 3 3 0 2 0 3 2 3
 3 1 0 1 0 3 0 1 0 2 2 1 3 1 3 0 3 1 2 0 0 2 1 3 3 3 1 1 3 0 0 2 3 3 1 3 1
 1 3 2 1 2 3 3 3 1 0 0 2 3 1 1 3 2 1 3 0 0 3 1 0 3 2 3 3 2 1 3 3 2 3 1 2 1
 2 0 2 3 1 0 0 3 0 3 0 1 2 0 2 3 1 3 2 2 1 2 0 0 0 1 3 2 0 0 0 3 2 0 2 3 1
 2 2 2 3 1 3 3 2 2 2 3 3 0 3 0 3 1 3 1 2 3 0 1 0 3 1 3 2 3 0 0 0 0 2 0 0 2
 2 1 2 2 2 0 1 0 0 3 2 0 3 1 2 2 1 2 3 1 1 2 2 1 2 0 1 1 0 3 2 1 0 1 0 0 1
 1 0 0 0 2 2 3 2 3 0 3 0 3 0 1 1 0 2 0 3 2 3 3 1 3 1 3 1 2 2 0 1 2 1 1 0 0
 0 1 2 1 0 3 2 0 2 2 0 0 3 1 2 0 2 3 3 0 3 0 2 3 2 3 0 2 0 2 3 0 1 1 0 0 1
 1 1 3 3 3 2 3 1 2 2 3 3 

In [ ]:
df = pd.DataFrame(data={"id": ran, "price_range": pred})
df.to_csv("loan_answer.csv",index=False)